### ISSUE TITLE
 用不了啊

### ISSUE THREAD

**Issue by liangnansheng** [limedroid/ARecyclerView#1]
用不了你的库

**Comment by limedroid** [comment]
请详细说下。。我上面是有demo的，就是app module

**Comment by cocpublic** [comment]
demo中的mainActivity 中向上滑动触发 加载更多时  “加载中”的footer没有显示，我集成到项目中也有同样的问题，debug是，simpleLoadingView的 onLoading却走了，但是 footer就是没出来,

**Comment by cocpublic** [comment]
方便给个联系方式没 ，直接请教你

**Comment by limedroid** [comment]
感谢您的反馈，我提交了下，你看看。 @cocpublic  @liangnansheng

**Comment by limedroid** [comment]
已修复
