### ISSUE TITLE
下拉刷下的时候会触发加载更多的监听事件，没有判断这两个事件的互斥状态么？

### ISSUE THREAD

**Issue by namelin2** [limedroid/ARecyclerView#4]
![issue001](https://cloud.githubusercontent.com/assets/17449099/21002330/25b449d6-bd60-11e6-8888-7b046f004875.png)

**Comment by limedroid** [comment]
暂时没有判断

**Comment by lodgkk** [comment]
那个应该是由于item太少,所以加载更多按钮展示出来了,导致自动加载了,你可以加一个布尔值全局变量,先隐藏底部,当获取到第一页数据的时候再显示出来,再自动加载

**Comment by limedroid** [comment]
这两个问题在v1.1.0版本已修复 @namelin2 @lodgkk
