### ISSUE TITLE
发现了两个坑。。求修复

### ISSUE THREAD

**Issue by yangkile** [limedroid/ARecyclerView#7]
XrecyclerviewContentLayout 禁用刷新后，再度下拉，又会触发recyclerview的滚动监听，在最下面又将setEnabale设为true 刷新禁用又变成了启用。这个问题很大。。。

Arecyclerview中，加载的时候会默认展示一个viewholder的布局，原版的recyclerview不会默认展示啊，这问题是出在了哪？

**Comment by yangkile** [comment]
![image](https://cloud.githubusercontent.com/assets/18137686/22106209/97e631b6-de82-11e6-8605-c16c751778a6.png)
发现问题2的原因了。。之前未转移库的时候。。maven库里面那个少了一句代码。。
![image](https://cloud.githubusercontent.com/assets/18137686/22106239/c76b4cc8-de82-11e6-9949-a794d910d18c.png)
新版的jitpack已经添加进去

**Comment by limedroid** [comment]
这个问题在最新的v1.1.0版本已修复 @yangkile
