### ISSUE TITLE
报！又发现一重大bug,动画时间造成的白屏

### ISSUE THREAD

**Issue by yangkile** [limedroid/ARecyclerView#8]
XSTATECONTROLER 的 animationState 

因为动画设置了时常0.3 秒，动画开始时 进入view 显示  结束时出view隐藏

当加载时间过快，animationState连续调用两次，，从content状态转移到loading（A状态），在从loading状态 转换为 content状态（B状态）

动画开始 两个view 同时显示 ，再隔0.3秒动画完毕 出view 同时隐藏

然而exitview A状态下是loadingview B状态下是swiprefreshview，结束动画时，同时隐藏后啥都没了，都不显示白屏了。。。

**Comment by limedroid** [comment]
感谢你的反馈，我会尽快修复。@yangkile

**Comment by limedroid** [comment]
提交了一下  @yangkile
