### ISSUE TITLE
网格设置setSpanSizeLookup无效。

### ISSUE THREAD

**Issue by 50kg** [limedroid/ARecyclerView#9]
GridLayoutManager manager = new GridLayoutManager(getContext(), 2);
                    manager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
                        @Override
                        public int getSpanSize(int position) {
                            Log.d(TAG, "getSpanSize: " + position);
                            Object object = items.get(position);
                            return object instanceof LiveBean.DataBean.PartitionsBean.LivesBean ? 2 : 0;
                        }
                    });

设置无效，谢谢亲

**Comment by limedroid** [comment]
谢谢反馈：查看XRecyclerView源码就可发现，setAdapter的时候已经setSpanSizeLookup，如果需要重新设置，建议先设置为null，然后将源码中的那部分逻辑和自己的逻辑整合起来。@50kg

**Comment by 50kg** [comment]
@limedroid 是libary设置为null吗？

**Comment by 50kg** [comment]
不太会改。。求修复。

**Comment by limedroid** [comment]
这本身不是一个bug，你加我q吧  1028101430 @50kg
